server:
  port: 8080

mybatis:
  type-aliases-package: com.tws.springbootdemo.entity
  mapper-locations: classpath:mapping/*Mapper.xml


spring:
  datasource:
    druid:
      type: com.alibaba.druid.poll.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # 是否缓存preparedStatement，也就是PSCache。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: -1
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      validation-query: SELECT 'x'
      # 单位：秒，检测连接是否有效的超时时间。
      validation-query-timeout: 1
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 6000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 1800000
      # 监控页面相关配置
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      # filter相关配置
#      filter:
#        stat:
#          slow-sql-millis: 1000
#          log-slow-sql: true
#          enabled: true
#        log4j:
#          enabled: true
#          result-set-log-enabled: false
#          connection-log-enabled: false
#          statement-parameter-clear-log-enable: false
#          statement-close-after-log-enabled: false
#          statement-create-after-log-enabled: false
#          statement-parameter-set-log-enabled: false
#          statement-prepare-after-log-enabled: false


  redis:
    host: localhost
    port: 6379
    timeout: 20000
    pool:
        # 连接池最大连接数
      max-active: 8
        # 连接池中的最小空闲连接
      min-idle: 0
        # 连接池中的最大空闲连接
      max-idle: 8
        #连接池最大阻塞等待时间
      max-wait: -1
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /mall
#    username: mall
#    password: mall
    #publisher-confirms: true #如果对异步消息需要回调必须设置为true

jwt:
  tokenHead: Bearer
  tokenHeader: Authorization
  expiration: 5184000
  secret: aHR0cHM6Ly9teS5vc2NoaW5hLm5ldC91LzM2ODE4Njg=

